import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:company/model/model.dart';

Future<List<EmployeeData>>fetchEmployeeData() async {
  final response =
      await http.get(Uri.parse('https://jsonplaceholder.typicode.com/users'));

  if (response.statusCode == 200) {
    final parsed = json.decode(response.body).cast<Map<String, dynamic>>();

    return parsed.map<EmployeeData>((json) => EmployeeData.fromMap(json)).toList();
  } else {
    throw Exception('Failed to load album');
  }
}

















































































































// import 'dart:convert';

// import 'package:company/model/model.dart';
// import 'package:http/http.dart' as http;
// import 'package:flutter/material.dart';
// import 'package:company/view/homescreen.dart';
// // Future<Autogenerated> fetchAutogenerated() async {
// //  // List details=[];
// //   final response = await http
// //       .get(Uri.parse('https://run.mocky.io/v3/bdcdffd7-df4c-4645-8290-d451ea6fe98a'));
// class apicall{
//   List id=[];
//   var idUrl='https://run.mocky.io/v3/bdcdffd7-df4c-4645-8290-d451ea6fe98a';
//   Future<List>getprofile()async{
//     http.Response res=await http.get(Uri.parse(idUrl));

//   try{
//   if (res.statusCode == 200) {
//    List<dynamic>pro=jsonDecode(res.body);
//     return pro.map((e)=>Autogenerated.fromJson(e)).toList();
//   } else {
//    return [];
//     // throw Exception('Failed to load album');
//   }}
//   catch(e){
//   return[];}
//   }
// }







// // Future<http.Response> fetchAutogenerated() {
// //   return http.get(Uri.parse('https://run.mocky.io/v3/bdcdffd7-df4c-4645-8290-d451ea6fe98a'));
  
// // }










